trigger:
- master


jobs:

- job: 'Test'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: PowerShell@2
    inputs:
      filePath: 'script_no_params.ps1'
      displayName: 'Run Robot Scripts'
      
  - script: pip install robotframework robotframework-seleniumlibrary && pip install chromedriver && pip install Microsoft.Powershell --source winget
    displayName: 'Install dependencies'
  
  - powershell: robot --pythonpath . test.robot


