trigger:
- master

pool:
  vmImage: 'windows-2019'

jobs:
  InstallationPython:
    runs-on: 'windows-2019'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'

  Installation Robot:
    runs-on: 'windows-2019'
    steps:
      - name: install robotframework
        run: pip install robotframework robotframework-seleniumlibrary && pip install chromedriver
      - name: Copy DockerFile
        run: cp . .
      - name: run robot
        run: robot --pythonpath . -x outputxunit.xml . test.robot
